services:
  nerfstudio:
    build:
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: nerfstudio:v1
    container_name: nerfstudio
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /dev/:/dev/
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTH_PATH}:/root/.Xauthority:rw
      - ${CACHE_PATH}/:/home/root/.cache/
      - ${WORKSPACE_ROOT}:/workspace/
    shm_size: "12gb"
    network_mode: host
    privileged: true